spring:
  data:
    cassandra:
      contact-points: ${CASSANDRA_HOSTS:cassandra-cluster.prod.chase.com}
      port: ${CASSANDRA_PORT:9042}
      keyspace-name: transaction_platform_prod
      username: ${CASSANDRA_USERNAME}
      password: ${CASSANDRA_PASSWORD}
      ssl:
        enabled: true
      request:
        timeout: PT5S
        consistency: LOCAL_QUORUM
    connection:
      pool:
        local:
          core: 8
          max: 16
        remote:
          core: 4
          max: 8

server:
  tomcat:
    threads:
      max: 400
      min-spare: 20
    accept-count: 200
    max-connections: 16384

logging:
  level:
    root: WARN
    com.chase.transactionplatform: INFO
    org.springframework.security: WARN
  file:
    name: /var/log/transaction-platform/transaction-platform-processor.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 3GB

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus

transaction-platform:
  kafka:
    topic: transactions.platform.prod
    partitions: 24
    replication-factor: 3
  validation:
    max-amount: 10000000.00
    min-amount: 0.01
  cache:
    ttl: PT5M
    max-size: 50000

aurora:
  async:
    core-pool-size: 20
    max-pool-size: 100
    queue-capacity: 2000 